"""Configuration-driven starter model generation."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any

from .config import dump_config


ROOT = Path(__file__).resolve().parents[1]


@dataclass(frozen=True)
class ModelSpec:
    name: str
    source_template: str
    description: str


MODEL_SPECS: dict[str, ModelSpec] = {
    "mantle_convection": ModelSpec("mantle_convection", "beginner_2d_box_convection.prm", "2-D thermal mantle convection starter model"),
    "subduction": ModelSpec("subduction", "beginner_subduction.prm", "2-D runnable kinematically driven subduction starter model"),
    "rift": ModelSpec("rift", "beginner_rift.prm", "2-D continental extension/rift starter model"),
}


def list_models() -> list[dict[str, str]]:
    return [{"type": k, "description": v.description} for k, v in sorted(MODEL_SPECS.items())]


def create_model(config: dict[str, Any], output_dir: Path | None = None) -> Path:
    model = config.get("model", {})
    if not isinstance(model, dict):
        raise ValueError("config.model must be a mapping")
    model_type = str(model.get("type", "")).strip()
    if model_type not in MODEL_SPECS:
        raise ValueError(f"Unsupported P0 model type: {model_type}. Supported: {', '.join(MODEL_SPECS)}")
    case_name = str(model.get("case_name") or f"{model_type}_case")
    case_dir = (output_dir or Path(case_name)).resolve()
    case_dir.mkdir(parents=True, exist_ok=True)
    (case_dir / "output").mkdir(exist_ok=True)
    spec = MODEL_SPECS[model_type]
    src = ROOT / "assets" / "prm_templates" / spec.source_template
    prm_text = _apply_common_overrides(src.read_text(encoding="utf-8"), config, model_type)
    (case_dir / "case.prm").write_text(prm_text, encoding="utf-8")
    dump_config(config, case_dir / "config.yaml")
    _write_run_sh(case_dir)
    _write_readme(case_dir, spec)
    return case_dir


def _replace_set(text: str, name: str, value: str) -> str:
    lines = []
    replaced = False
    for line in text.splitlines():
        stripped = line.strip()
        if stripped.startswith(f"set {name}") and "=" in stripped:
            prefix = line[: len(line) - len(line.lstrip())]
            lines.append(f"{prefix}set {name} = {value}")
            replaced = True
        else:
            lines.append(line)
    if not replaced:
        lines.insert(0, f"set {name} = {value}")
    return "\n".join(lines) + "\n"


def _apply_common_overrides(text: str, config: dict[str, Any], model_type: str) -> str:
    model = config.get("model", {}) if isinstance(config.get("model"), dict) else {}
    thermal = config.get("thermal", {}) if isinstance(config.get("thermal"), dict) else {}
    case_name = str(model.get("case_name") or f"{model_type}_case")
    text = _replace_set(text, "Output directory", "output")
    if "end_time_years" in model:
        text = _replace_set(text, "End time", str(model["end_time_years"]))
    if "surface_temperature" in thermal:
        text = text.replace("set Top temperature    = 273", f"set Top temperature    = {thermal['surface_temperature']}")
    if "mantle_temperature" in thermal:
        text = text.replace("set Bottom temperature = 1573", f"set Bottom temperature = {thermal['mantle_temperature']}")
        text = text.replace("set Bottom temperature = 1673", f"set Bottom temperature = {thermal['mantle_temperature']}")
    header = [
        f"# Generated by Aspect_Yuan model generator for {model_type}.",
        f"# Case name: {case_name}",
        "# This is a starter model for learning and smoke testing, not a final research model.",
        "# Verify with ASPECT before scientific interpretation.",
    ]
    return "\n".join(header) + "\n\n" + text


def _write_run_sh(case_dir: Path) -> None:
    path = case_dir / "run.sh"
    path.write_text('#!/usr/bin/env bash\nset -euo pipefail\nASPECT_BIN="${ASPECT_BIN:-aspect}"\n"$ASPECT_BIN" case.prm 2>&1 | tee run.log\n', encoding="utf-8")
    path.chmod(0o755)


def _write_readme(case_dir: Path, spec: ModelSpec) -> None:
    (case_dir / "README.md").write_text(
        f"""# {case_dir.name}

Model type: `{spec.name}`

Geological meaning: {spec.description}.

```bash
aspect-yuan model validate case.prm
./run.sh
aspect-yuan postprocess scan output
```
""",
        encoding="utf-8",
    )
